CREATE DATABASE DOG_MANAGEMENT_HCMC
GO
USE DOG_MANAGEMENT_HCMC
GO
CREATE TABLE PERSONINFO
(
	IDPERSON VARCHAR(5),
	IDCARDNUM VARCHAR(20),
	ADDRESS NVARCHAR(100),
	BIRHDAY DATE,
	EMAIL NVARCHAR(50),
	PHONENUM VARCHAR(20),
	NAME NVARCHAR(50),
	GENDER BIT DEFAULT 1,
	TYPEPSI BIT--loại thông tin 1: user 0 : chủ chó
	PRIMARY KEY (IDPERSON)
)
GO

CREATE TABLE ACCOUNT
(
	USERNAME VARCHAR(10) PRIMARY KEY,
	PASSWORD VARCHAR(100) DEFAULT '1',
	PASSWORD2 VARCHAR(100) DEFAULT '2',
	TYPE INT NOT NULL,
	ISLOCK BIT DEFAULT 0

)

GO

CREATE TABLE USERAPP
(
	IDPERSON VARCHAR(5),
	BANKNUM VARCHAR(20),
	MEDICALCODE VARCHAR(20), --MÃ BAO HIEM Y TE
	ACCOUNT VARCHAR(10),
	FRINGEBENEFIT INT , -- PHU CAP 
	DATEJOIN DATE, --NGAY VAO CTY
	BASICSALARY INT DEFAULT 0--  LƯƠNG CƠ BẢN
	PRIMARY KEY(IDPERSON,BANKNUM,ACCOUNT)
	FOREIGN KEY (IDPERSON) REFERENCES dbo.PERSONINFO(IDPERSON),
	FOREIGN KEY (ACCOUNT) REFERENCES dbo.ACCOUNT(USERNAME)
)

GO
CREATE TABLE DOG
(
	IDDOG INT IDENTITY,
	WEIGHT INT DEFAULT 1,
	TYPE INT NOT NULL,
	DATEINT DATE NOT NULL,
	DATEOUT DATE,
	ISINJECT BIT DEFAULT 0,
	FOODMONEY INT
	PRIMARY KEY (IDDOG)
)

GO

CREATE TABLE DOGDETROYED
(
	IDDOG INT IDENTITY,
	DATEDETROYED DATE NOT NULL,
	IDSTAFF VARCHAR(5)
	PRIMARY KEY (IDDOG,DATEDETROYED,IDSTAFF),
	FOREIGN KEY (IDDOG) REFERENCES dbo.DOG(IDDOG),
	FOREIGN KEY (IDSTAFF) REFERENCES dbo.PERSONINFO(IDPERSON)
)

GO

CREATE TABLE dboDOGOWNER
(
	IDDOGOWNER VARCHAR(5),
	IDDOG INT NOT NULL
	PRIMARY KEY (IDDOGOWNER,IDDOG),
	FOREIGN KEY (IDDOGOWNER) REFERENCES dbo.PERSONINFO(IDPERSON),
	FOREIGN KEY (IDDOG) REFERENCES dbo.DOG(IDDOG)
)
GO
CREATE TABLE BILL
(
	IDBILL INT IDENTITY NOT NULL,
	DAYBILL DATE NOT NULL,
	IDOWNER VARCHAR(5),
	FINE INT NOT NULL,
	IDSTAFF VARCHAR(5)
	PRIMARY KEY (IDBILL)
	FOREIGN KEY (IDSTAFF) REFERENCES dbo.PERSONINFO(IDPERSON),
	FOREIGN KEY (IDOWNER) REFERENCES dbo.PERSONINFO(IDPERSON)

)

---------------------DATA TEST
INSERT dbo.ACCOUNT VALUES(   N'ADMIN', N'1', N'ADMIN', 1, 0)
INSERT dbo.ACCOUNT VALUES(   N'FICUONG', N'1', N'CUONG', 1, 0)

INSERT dbo.ACCOUNT VALUES(   N'NGOC', N'PASS', N'NGOC', 2, 0)
INSERT dbo.ACCOUNT VALUES(   N'DAT', N'PASS', N'DATE', 2, 1)

INSERT dbo.ACCOUNT VALUES(   N'HUE', N'PASS', N'HUE', 3, 0)

				
INSERT 	dbo.DOG(   WEIGHT,    TYPE,    DATEINT,    DATEOUT,    ISINJECT,    FOODMONEY)
VALUES(     5,       1,      '11/22/2017',     GETDATE(),     NULL,       0    )	

INSERT 	dbo.DOG(  WEIGHT,    TYPE,    DATEINT,    DATEOUT,    ISINJECT,    FOODMONEY)
VALUES(    10,       3,      '11/20/2017',     GETDATE(),     NULL,       0    )	

INSERT 	dbo.DOG(    WEIGHT,    TYPE,    DATEINT,    DATEOUT,    ISINJECT,    FOODMONEY)
VALUES(     8,       2,      '11/21/2017',     GETDATE(),     NULL,       0    )	

INSERT 	dbo.DOG(    WEIGHT,    TYPE,    DATEINT,    DATEOUT,    ISINJECT,    FOODMONEY)
VALUES(    2,       1,      '11/19/2017',     GETDATE(),     NULL,       0    )	
	

INSERT 	dbo.DOG(    WEIGHT,    TYPE,    DATEINT,    DATEOUT,    ISINJECT,    FOODMONEY)
VALUES(     15,       2,      '11/23/2017',     GETDATE(),     NULL,       0    )	

INSERT 	dbo.DOG(  WEIGHT,    TYPE,    DATEINT,    DATEOUT,    ISINJECT,    FOODMONEY)
VALUES(     2,       1,      '11/22/2017',     GETDATE(),     NULL,       0    )	

INSERT 	dbo.DOG(   WEIGHT,    TYPE,    DATEINT,    DATEOUT,    ISINJECT,    FOODMONEY)
VALUES(      20,       3,      '11/20/2017',     GETDATE(),     NULL,       0    )	

INSERT 	dbo.DOG(    WEIGHT,    TYPE,    DATEINT,    DATEOUT,    ISINJECT,    FOODMONEY)
VALUES(      3,       3,      '03/23/2017',     GETDATE(),     NULL,       0    )	

INSERT dbo.PERSONINFO(IDPERSON, IDCARDNUM, ADDRESS,  BIRHDAY,  EMAIL, PHONENUM,  NAME, GENDER, TYPEPSI)
VALUES( 'QL001', '281157576',  N'57 TÂN KHAI, P4, Q11',   '04/17/1997',  N'NFICUONG@GMAIL.COM',
 '01638406801' ,  N'NGUYỄN PHI CƯỜNG', 0, 1  )

INSERT dbo.PERSONINFO (IDPERSON,  IDCARDNUM, ADDRESS,  BIRHDAY,  EMAIL, PHONENUM,  NAME, GENDER, TYPEPSI)
VALUES('NV001', '281157522',  N'123 ÂU CƠ, Q.TÂN PHÚ',   '08/17/1996',  N'NTNGOC@GMAIL.COM',
'093653665'  ,   N'nGUYỄN THỊ NGỌC',  1,1)

INSERT dbo.PERSONINFO(IDPERSON, IDCARDNUM, ADDRESS,  BIRHDAY,  EMAIL, PHONENUM,  NAME, GENDER,TYPEPSI)
VALUES('KT001', '281124247',  N'13/37 TRẦN VĂN HOÀN',   '11/11/1997',  N'DOGHUE@GMAIL.COM',
'0165354452' ,   N'ẲNG THỊ QUẸ', 1,1)

INSERT dbo.PERSONINFO(IDPERSON, IDCARDNUM, ADDRESS,  BIRHDAY,  EMAIL, PHONENUM,  NAME, GENDER,TYPEPSI)
VALUES('ON001',281157571,  N'45 TÔ HIẾN THÀNH P2 Q10',   NULL, N'','',N'', 1,0)

INSERT dbo.PERSONINFO(IDPERSON, IDCARDNUM, ADDRESS,  BIRHDAY,  EMAIL, PHONENUM,  NAME, GENDER,TYPEPSI)
VALUES('ON002', '281154546',  N'LINH TRUNG THỦ ĐỨC',   NULL, N'LINHTRUNG@GMAIL.COM','',N'LÝ HIỂN LONG', 1,0)

INSERT dbo.USERAPP
VALUES('QL001', '9516238478521',   '1596238',   N'ADMIN',  8,   '11/21/2012',  0  )

INSERT dbo.USERAPP
VALUES('NV001','9854784123025',  '1598745',   N'NGOC',  5,   '11/21/2015',  0  )

INSERT dbo.USERAPP
VALUES('KT001','9852365101478',  '7851203',   N'HUE',  6,   '01/28/2014',  0  )


INSERT dbo.dboDOGOWNER VALUES( 'ON001'  ,   002  )

ALTER TABLE dbo.USERAPP ADD IMG IMAGE


DELETE FROM dbo.PERSONINFO WHERE IDPERSON = N'QL003'